// frontend-react/src/components/SelectImageModal.tsx
import {
    Dialog,
    DialogContent,
    DialogDescription,
    DialogHeader,
    DialogTitle,
    DialogTrigger,
    DialogClose,
} from "@/components/ui/dialog"
import { useImages } from "@/hooks/useImages"
import { ImageDown } from "lucide-react"

interface SelectImageModalProps {
    onChange: (url: string) => void
}

export default function SelectImageModal({ onChange }: SelectImageModalProps) {
    const { images, isLoading } = useImages()

    return (
        <Dialog>
            <DialogTrigger asChild>
                <button
                    type="button"
                    className="flex items-center gap-2 px-4 py-2 rounded-lg border border-neutral-700 text-neutral-300 hover:bg-neutral-800 transition-colors text-sm cursor-pointer"
                >
                    <ImageDown size={16} />
                    Select Image
                </button>
            </DialogTrigger>
            <DialogContent className="max-w-[600px]">
                <DialogHeader>
                    <DialogTitle>Select Image</DialogTitle>
                    <DialogDescription className="sr-only">Select Image</DialogDescription>
                </DialogHeader>
                <div className="max-h-[500px] overflow-auto flex flex-wrap gap-2 items-center">
                    {isLoading && <p className="text-neutral-400 p-4">Loading...</p>}
                    {!isLoading && images?.length === 0 && (
                        <p className="text-neutral-400 p-4">No images uploaded yet.</p>
                    )}
                    {images?.map((item, index) => (
                        <DialogClose key={index} asChild>
                            <button
                                type="button"
                                onClick={() => onChange(item.url)}
                                className="cursor-pointer hover:opacity-80 transition-opacity"
                            >
                                <img
                                    src={item.url}
                                    alt={`Image ${index + 1}`}
                                    className="aspect-video h-[50px] rounded-sm object-cover"
                                />
                            </button>
                        </DialogClose>
                    ))}
                </div>
            </DialogContent>
        </Dialog>
    )
}

// frontend/src/components/SelectImageModal.vue
<script setup lang="ts">
import { Button } from "@/components/ui/button"
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
} from "@/components/ui/dialog"
import { useUploadImage } from "@/hooks/useUploadImage"
import { createReusableTemplate } from "@vueuse/core"
import { ref } from "vue"
import DialogClose from "./ui/dialog/DialogClose.vue"
import { useImages } from "@/hooks/useImages"

const { images } = useImages()
const emit = defineEmits<{
  change: [url: string]
}>()
</script>

<template>
  <Dialog>
    <DialogTrigger as-child>
      <Button>Select Image</Button>
    </DialogTrigger>
    <DialogContent class="max-w-[600px]">
      <DialogHeader>
        <DialogTitle>Select Image</DialogTitle>
        <DialogDescription hidden> Select Image </DialogDescription>
      </DialogHeader>
      <div class="max-h-[500px] overflow-auto flex flex-wrap gap-2 items-center">
        <DialogClose v-for="(item, index) in images" @click="emit('change', item.url)">
          <img :key="index" :src="item.url" class="aspect-video h-[50px] rounded-sm" />
        </DialogClose>
      </div>
    </DialogContent>
  </Dialog>
</template>
