// frontend/src/components/PostAside.vue
<script setup lang="ts">
import { useTags } from "@/hooks/useTags"
import PostTag from "./PostTag.vue"
import { computed } from "vue"
import { useRoute, useRouter } from "vue-router"
import { useTranslation } from "i18next-vue"

const { tagString } = useTags()
const router = useRouter()
const route = useRoute()
const { t } = useTranslation()
const tags = computed(() => tagString.value?.split(","))
const handleClick = (item: string) => {
  router.push({ query: { tag: item } })
  if (item === route.query.tag) {
    router.replace({ query: undefined })
  }
}
</script>

<template>
  <aside class="mt-8 md:sticky md:top-16 md:h-fit md:self-start text-white text-sm">
    <p>{{ t("posts.tag") }}</p>
    <div class="flex flex-wrap mt-4">
      <PostTag
        v-for="(item, index) in tags"
        :key="index"
        class="cursor-pointer transition-colors duration-300 m-1"
        :class="route.query.tag === item ? '!bg-accent/30 !text-accent' : 'hover:text-white'"
        @click="handleClick(item)"
      >
        {{ item }}
      </PostTag>
    </div>
  </aside>
</template>

// frontend-react/src/components/PostAside.tsx
import { useTags } from "@/hooks/useTags"
import PostTag from "./PostTag"
import { useSearchParams } from "react-router-dom"
import { useTranslation } from "react-i18next"
import { cn } from "@/lib/utils"

export default function PostAside() {
    const { tagString } = useTags()
    const [searchParams, setSearchParams] = useSearchParams()
    const { t } = useTranslation()
    const tags = tagString?.split(",") || []
    const currentTag = searchParams.get("tag")

    const handleClick = (item: string) => {
        if (currentTag === item) {
            searchParams.delete("tag")
            setSearchParams(searchParams)
        } else {
            setSearchParams({ tag: item })
        }
    }

    return (
        <aside className="mt-8 md:sticky md:top-16 md:h-fit md:self-start text-white text-sm">
            <p>{t("posts.tag")}</p>
            <div className="flex flex-wrap mt-4">
                {tags.map((item, index) => (
                    <div
                        key={index}
                        className="cursor-pointer transition-colors duration-300 m-1"
                        onClick={() => handleClick(item)}
                    >
                        <PostTag
                            className={cn(
                                currentTag === item ? "!bg-accent/30 !text-accent" : "hover:text-white"
                            )}
                        >
                            {item}
                        </PostTag>
                    </div>
                ))}
            </div>
        </aside>
    )
}
